apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-depl
  namespace: default
spec:
  selector:
    matchLabels:
      app: myapp-depl
  template:
    metadata:
      labels:
        app: myapp-depl
    spec:
      containers:
        - name: myapp-depl
          image: nginx:alpine
          resources:
            limits:
              memory: "64Mi"
              cpu: "100m"
          ports:
            - containerPort: 80
