apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mygrafana
  # namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: grafana #ambil dari https://github.com/grafana/helm-charts/blob/main/charts/grafana/README.md
      # version: "4.0.x"
      sourceRef:
        kind: HelmRepository
        name: grafana
        # namespace: flux-system
      interval: 1m
  values:
    replicas: 2
