apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: payment-service
spec:
  interval: 5m
  chart:
    spec:
      chart: .helm/application
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 1m
  values:
    image:
      name: httpd
      tags: latest
